# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty         
relative_permalinks: false

# Setup
title:               Curious & Exploring
tagline:             'There is a story there, I think.'
description:         'This is probably a bad idea. But I will do it anyway. Created by @rishigb'
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Rishi Gaurav Bhatnagar
  url:               https://twitter.com/rishigb 
  email:             rishibhatnagar1@gmail.com

# Custom vars
version:             1.0.0

#Social Media Stuff
twitter_username:     rishigb
github_username:      rishigb
linkedin_username:    
google_plus_username: 
facebook_username:    