# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty         
relative_permalinks: false

# Setup
title:               Curious explorations
tagline:             'There is a story there, I think.'
description:         'This is probably a bad idea.'
url:                 
baseurl:             'http://rishigb.github.io/'
paginate:            5

# About/contact
author:
  name:              Rishi Gaurav Bhatnagar
  url:               https://twitter.com/rishigb 
  email:             rishibhatnagar1@gmail.com

# Custom vars
version:             1.0.0
